In [14]:
#Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

import numpy as np

A = np.array([[10,22,23,],[4,7,6]])
B = np.array([[23,28,9],[10,5,12]])

# Stack A and B vertically
v_stack = np.vstack((A,B))

# Stack A and B horizontally 
h_stack = np.hstack((A,B))


print("A: ")
print(v_stack)

print("B: ")
print(h_stack)

A: 
[[10 22 23]
 [ 4  7  6]
 [23 28  9]
 [10  5 12]]
B: 
[[10 22 23 23 28  9]
 [ 4  7  6 10  5 12]]


In [17]:
# Flatten the NumPy arrays and convert them to sets (convert a multi-demensional array to one-demensional array)
set_A = set(A.flatten())
set_B = set(B.flatten())

# Find the common elements (intersection)
common_elements = set_A.intersection(set_B)

# Convert the result back to a NumPy array
common_elements_array = np.array(list(common_elements))

print("A:")
print(A)

print("B:")
print(B)

print("Common Elements:")
print(common_elements_array)

A:
[[10 22 23]
 [ 4  7  6]]
B:
[[23 28  9]
 [10  5 12]]
Common Elements:
[10 23]


In [20]:
#Extract all numbers from A which are within a specific range. eg between 5 and 10. 
#[Hint: np.where() might be useful or boolean masks]

# Create a custom NumPy array A
A = np.array([[10, 22, 23], [4, 7, 6]])

# Define the specific range
lower_limit = 5
upper_limit = 10

# Create a Boolean mask for the elements within the specified range
mask = (A >= lower_limit) & (A <= upper_limit)

# Use the mask to extract the elements within the range
elements_in_range = A[mask]

print("A:")
print(A)

print("Numbers in the range (5,10) ")
print(elements_in_range)

A:
[[10 22 23]
 [ 4  7  6]]
Numbers in the range (5,10) 
[10  7  6]


In [22]:
#Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# Create a Boolean mask to filter the rows
mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

# Use the mask to filter the rows of iris_2d
filtered_rows = iris_2d[mask]

print("Filtered Rows:")
print(filtered_rows)

Filtered Rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
